# Commands to start on workspace startup
tasks:
  - init: npm ci
    command: |
      npm run build
      npm start
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview

